name: Jest
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm run pull-merge -- ${{github.head_ref}}


# This is how you get the name of the branch
# that is merged into dev --> for Notion