name: Jest
on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm i
    - name: Run Jest
      working-directory: ./repo-webapp
      run: npm run test:ci
